#-------------------------------------------------
#
# Project created by QtCreator 2016-02-09T01:56:49
#
#-------------------------------------------------

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = Skyrim_Behavior_Tool
TEMPLATE = app

# remove possible other optimization flags
#QMAKE_CXXFLAGS_DEBUG -= -O
#QMAKE_CXXFLAGS_DEBUG -= -O1
#QMAKE_CXXFLAGS_DEBUG -= -O2

# add the desired -O3 if not present
#QMAKE_CXXFLAGS_DEBUG *= -O3


VERSION = 0.90
QMAKE_TARGET_COMPANY = WK Inc.
#QMAKE_TARGET_PRODUCT = "Skyrim Behavior Editor"
QMAKE_TARGET_DESCRIPTION = Skyrim Behavior Editor
QMAKE_TARGET_COPYRIGHT = Wayne K

SOURCES += \
    src/main.cpp \
    src/filetypes/hkxfile.cpp \
    src/ui/mainwindow.cpp \
    src/xml/hkxxmlreader.cpp \
    src/hkxclasses/behavior/hkbbehaviorgraphstringdata.cpp \
    src/hkxclasses/hkxobject.cpp \
    src/hkxclasses/behavior/hkbvariablevalueset.cpp \
    src/hkxclasses/behavior/hkbbehaviorgraphdata.cpp \
    src/hkxclasses/behavior/generators/hkbbehaviorgraph.cpp \
    src/hkxclasses/behavior/generators/hkbgenerator.cpp \
    src/hkxclasses/hkrootlevelcontainer.cpp \
    src/hkxclasses/behavior/generators/hkbbehaviorreferencegenerator.cpp \
    src/hkxclasses/behavior/generators/hkbstatemachine.cpp \
    src/hkxclasses/behavior/generators/hkbstatemachinestateinfo.cpp \
    src/hkxclasses/behavior/generators/hkbclipgenerator.cpp \
    src/hkxclasses/behavior/generators/bscyclicblendtransitiongenerator.cpp \
    src/hkxclasses/behavior/generators/hkbblendergenerator.cpp \
    src/hkxclasses/behavior/generators/hkbblendergeneratorchild.cpp \
    src/hkxclasses/behavior/generators/hkbmanualselectorgenerator.cpp \
    src/hkxclasses/behavior/generators/hkbmodifiergenerator.cpp \
    src/hkxclasses/behavior/generators/bsboneswitchgenerator.cpp \
    src/hkxclasses/behavior/generators/bsboneswitchgeneratorbonedata.cpp \
    src/hkxclasses/behavior/generators/bsistatetagginggenerator.cpp \
    src/hkxclasses/behavior/generators/bssynchronizedclipgenerator.cpp \
    src/hkxclasses/behavior/generators/hkbposematchinggenerator.cpp \
    src/hkxclasses/behavior/generators/bsoffsetanimationgenerator.cpp \
    src/hkxclasses/behavior/hkbstringeventpayload.cpp \
    src/hkxclasses/behavior/hkbboneweightarray.cpp \
    src/hkxclasses/behavior/hkbstatemachineeventpropertyarray.cpp \
    src/hkxclasses/behavior/hkbstatemachinetransitioninfoarray.cpp \
    src/hkxclasses/behavior/modifiers/hkbmodifier.cpp \
    src/ui/hkxclassesui/hkdataui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/bsistatetagginggeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/modifiergeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/manualselectorgeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/behaviorvariablesui.cpp \
    src/ui/hkxclassesui/behaviorui/eventsui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/statemachineui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/stateui.cpp \
    src/hkxclasses/behavior/hkbvariablebindingset.cpp \
    src/ui/hkxclassesui/behaviorui/transitionsui.cpp \
    src/ui/hkxclassesui/behaviorui/blendingtransitioneffectui.cpp \
    src/hkxclasses/behavior/hkbexpressioncondition.cpp \
    src/ui/genericdatawidgets.cpp \
    src/xml/hkxxmlwriter.cpp \
    src/hkxclasses/behavior/hkbcliptriggerarray.cpp \
    src/hkxclasses/behavior/hkbblendingtransitioneffect.cpp \
    src/hkxclasses/behavior/modifiers/hkbmodifierlist.cpp \
    src/hkxclasses/behavior/modifiers/hkbtwistmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbeventdrivenmodifier.cpp \
    src/hkxclasses/behavior/modifiers/bsisactivemodifier.cpp \
    src/hkxclasses/behavior/modifiers/bslimbikmodifier.cpp \
    src/hkxclasses/behavior/modifiers/bsspeedsamplermodifier.cpp \
    src/hkxclasses/behavior/modifiers/bslookatmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbfootikcontrolsmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbevaluateexpressionmodifier.cpp \
    src/hkxclasses/behavior/hkbexpressiondataarray.cpp \
    src/hkxclasses/behavior/modifiers/bsmodifyoncemodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbrotatecharactermodifier.cpp \
    src/hkxclasses/behavior/modifiers/bseventondeactivatemodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbdampingmodifier.cpp \
    src/hkxclasses/behavior/modifiers/bseventonfalsetotruemodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbkeyframebonesmodifier.cpp \
    src/hkxclasses/behavior/hkbboneindexarray.cpp \
    src/hkxclasses/behavior/modifiers/bsragdollcontactlistenermodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbpoweredragdollcontrolsmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbtimermodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbrigidbodyragdollcontrolsmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbgetupmodifier.cpp \
    src/hkxclasses/behavior/modifiers/bsdirectatmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbcomputedirectionmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbevaluatehandlemodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbgethandleonbonemodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbsensehandlemodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbdelayedmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbdetectclosetogroundmodifier.cpp \
    src/hkxclasses/behavior/modifiers/bsdecomposevectormodifier.cpp \
    src/hkxclasses/behavior/generators/bgsgamebryosequencegenerator.cpp \
    src/hkxclasses/behavior/modifiers/bscomputeaddboneanimmodifier.cpp \
    src/hkxclasses/behavior/modifiers/bsdisttriggermodifier.cpp \
    src/hkxclasses/behavior/modifiers/bseventeveryneventsmodifier.cpp \
    src/hkxclasses/behavior/modifiers/bsgettimestepmodifier.cpp \
    src/hkxclasses/behavior/modifiers/bsinterpvaluemodifier.cpp \
    src/hkxclasses/behavior/modifiers/bspassbytargettriggermodifier.cpp \
    src/hkxclasses/behavior/modifiers/bstimermodifier.cpp \
    src/hkxclasses/behavior/modifiers/bstweenermodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbattachmentmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbattributemodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbcombinetransformsmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbcomputerotationfromaxisanglemodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbcomputerotationtotargetmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbeventsfromrangemodifier.cpp \
    src/hkxclasses/behavior/hkbeventrangedataarray.cpp \
    src/hkxclasses/behavior/modifiers/hkbextractragdollposemodifier.cpp \
    src/hkxclasses/behavior/hkbgeneratortransitioneffect.cpp \
    src/hkxclasses/behavior/modifiers/hkbgetworldfrommodelmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkblookatmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbmirrormodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbmovecharactermodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbtransformvectormodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbproxymodifier.cpp \
    src/hkxclasses/behavior/modifiers/bsistatemanagermodifier.cpp \
    src/filetypes/behaviorfile.cpp \
    src/filetypes/projectfile.cpp \
    src/filetypes/characterfile.cpp \
    src/filetypes/skeletonfile.cpp \
    src/hkxclasses/behavior/hkbprojectdata.cpp \
    src/hkxclasses/behavior/hkbprojectstringdata.cpp \
    src/hkxclasses/behavior/hkbmirroredskeletoninfo.cpp \
    src/hkxclasses/behavior/hkbcharacterstringdata.cpp \
    src/hkxclasses/behavior/hkbcharacterdata.cpp \
    src/hkxclasses/behavior/hkbfootikdriverinfo.cpp \
    src/hkxclasses/behavior/hkbhandikdriverinfo.cpp \
    src/hkxclasses/behavior/hkbstringcondition.cpp \
    src/ui/hkxclassesui/projectui.cpp \
    src/hkxclasses/animation/hkaanimationcontainer.cpp \
    src/hkxclasses/hksimplelocalframe.cpp \
    src/hkxclasses/animation/hkaskeleton.cpp \
    src/ui/hkxclassesui/behaviorui/boneweightarrayui.cpp \
    src/ui/hkxclassesui/behaviorui/characterpropertiesui.cpp \
    src/ui/hkxclassesui/behaviorui/skeletonui.cpp \
    src/ui/hkxclassesui/behaviorui/footikdriverinfoui.cpp \
    src/ui/hkxclassesui/behaviorui/footikdriverinfolegui.cpp \
    src/ui/hkxclassesui/behaviorui/handikdriverinfoui.cpp \
    src/ui/hkxclassesui/behaviorui/handikdriverinfohandui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/blendergeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/blendergeneratorchildui.cpp \
    src/ui/treegraphicsview.cpp \
    src/ui/treegraphicsscene.cpp \
    src/ui/treegraphicsitem.cpp \
    src/ui/dataiconmanager.cpp \
    src/ui/behaviorgraphview.cpp \
    src/ui/hkxclassesui/behaviorui/eventui.cpp \
    src/ui/hkxclassesui/behaviorui/behaviorgraphicon.cpp \
    src/ui/hkxclassesui/behaviorui/generators/behaviorgraphui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bslimbikmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/bsboneswitchgeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/bsboneswitchgeneratorbonedataui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/bsoffsetanimationgeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/bscyclicblendtransitiongeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/posematchinggeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/clipgeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/cliptriggerui.cpp \
    src/ui/hkxclassesui/behaviorui/animationsui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/bssynchronizedclipgeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/behaviorreferencegeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bsdirectatmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/movecharactermodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/rotatecharactermodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/evaluateexpressionmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/expressiondataarrayui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/modifierlistui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/eventdrivenmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/gethandleonbonemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/evaluatehandlemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/sensehandlemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/rangesui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bsdecomposevectormodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bsisactivemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/computedirectionmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bscomputeaddboneanimmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bsdisttriggermodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bsinterpvaluemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/computerotationtotargetmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/getupmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/getworldfrommodelmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/twistmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/timermodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/dampingmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/rigidbodyragdollcontrolsmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/boneindexarrayui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/poweredragdollcontrolsmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/combinetransformsmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/computerotationfromaxisanglemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/transformvectormodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/lookatmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/keyframebonesmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/keyframeinfoui.cpp \
    src/ui/hkxclassesui/behaviorui/legui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/footikcontrolsmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/mirrormodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/extractragdollposemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bstimermodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bsgettimestepmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/delayedmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bsragdollcontactlistenermodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bseventondeactivatemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bsspeedsamplermodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bspassbytargettriggermodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/bsboneui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bslookatmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/detectclosetogroundmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bseventeveryneventsmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bseventonfalsetotruemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bsmodifyoncemodifierui.cpp \
    src/hkxclasses/behavior/modifiers/hkbhandikcontrolsmodifier.cpp \
    src/ui/hkxclassesui/behaviorui/handui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/handikcontrolsmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bstweenermodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/bgsgamebryosequencegeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/eventsfromrangemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/eventrangedataui.cpp \
    src/filetypes/behaviorfile.cpp \
    src/filetypes/characterfile.cpp \
    src/filetypes/hkxfile.cpp \
    src/filetypes/projectfile.cpp \
    src/filetypes/skeletonfile.cpp \
    src/hkxclasses/animation/hkaanimationcontainer.cpp \
    src/hkxclasses/animation/hkaskeleton.cpp \
    src/hkxclasses/behavior/generators/bgsgamebryosequencegenerator.cpp \
    src/hkxclasses/behavior/generators/bsboneswitchgenerator.cpp \
    src/hkxclasses/behavior/generators/bsboneswitchgeneratorbonedata.cpp \
    src/hkxclasses/behavior/generators/bscyclicblendtransitiongenerator.cpp \
    src/hkxclasses/behavior/generators/bsistatetagginggenerator.cpp \
    src/hkxclasses/behavior/generators/bsoffsetanimationgenerator.cpp \
    src/hkxclasses/behavior/generators/bssynchronizedclipgenerator.cpp \
    src/hkxclasses/behavior/generators/hkbbehaviorgraph.cpp \
    src/hkxclasses/behavior/generators/hkbbehaviorreferencegenerator.cpp \
    src/hkxclasses/behavior/generators/hkbblendergenerator.cpp \
    src/hkxclasses/behavior/generators/hkbblendergeneratorchild.cpp \
    src/hkxclasses/behavior/generators/hkbclipgenerator.cpp \
    src/hkxclasses/behavior/generators/hkbgenerator.cpp \
    src/hkxclasses/behavior/generators/hkbmanualselectorgenerator.cpp \
    src/hkxclasses/behavior/generators/hkbmodifiergenerator.cpp \
    src/hkxclasses/behavior/generators/hkbposematchinggenerator.cpp \
    src/hkxclasses/behavior/generators/hkbstatemachine.cpp \
    src/hkxclasses/behavior/generators/hkbstatemachinestateinfo.cpp \
    src/hkxclasses/behavior/modifiers/bscomputeaddboneanimmodifier.cpp \
    src/hkxclasses/behavior/modifiers/bsdecomposevectormodifier.cpp \
    src/hkxclasses/behavior/modifiers/bsdirectatmodifier.cpp \
    src/hkxclasses/behavior/modifiers/bsdisttriggermodifier.cpp \
    src/hkxclasses/behavior/modifiers/bseventeveryneventsmodifier.cpp \
    src/hkxclasses/behavior/modifiers/bseventondeactivatemodifier.cpp \
    src/hkxclasses/behavior/modifiers/bseventonfalsetotruemodifier.cpp \
    src/hkxclasses/behavior/modifiers/bsgettimestepmodifier.cpp \
    src/hkxclasses/behavior/modifiers/bsinterpvaluemodifier.cpp \
    src/hkxclasses/behavior/modifiers/bsisactivemodifier.cpp \
    src/hkxclasses/behavior/modifiers/bsistatemanagermodifier.cpp \
    src/hkxclasses/behavior/modifiers/bslimbikmodifier.cpp \
    src/hkxclasses/behavior/modifiers/bslookatmodifier.cpp \
    src/hkxclasses/behavior/modifiers/bsmodifyoncemodifier.cpp \
    src/hkxclasses/behavior/modifiers/bspassbytargettriggermodifier.cpp \
    src/hkxclasses/behavior/modifiers/bsragdollcontactlistenermodifier.cpp \
    src/hkxclasses/behavior/modifiers/bsspeedsamplermodifier.cpp \
    src/hkxclasses/behavior/modifiers/bstimermodifier.cpp \
    src/hkxclasses/behavior/modifiers/bstweenermodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbattachmentmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbattributemodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbcombinetransformsmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbcomputedirectionmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbcomputerotationfromaxisanglemodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbcomputerotationtotargetmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbdampingmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbdelayedmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbdetectclosetogroundmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbevaluateexpressionmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbevaluatehandlemodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbeventdrivenmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbeventsfromrangemodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbextractragdollposemodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbfootikcontrolsmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbgethandleonbonemodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbgetupmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbgetworldfrommodelmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbhandikcontrolsmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbkeyframebonesmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkblookatmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbmirrormodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbmodifierlist.cpp \
    src/hkxclasses/behavior/modifiers/hkbmovecharactermodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbpoweredragdollcontrolsmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbproxymodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbrigidbodyragdollcontrolsmodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbrotatecharactermodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbsensehandlemodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbtimermodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbtransformvectormodifier.cpp \
    src/hkxclasses/behavior/modifiers/hkbtwistmodifier.cpp \
    src/hkxclasses/behavior/hkbbehaviorgraphdata.cpp \
    src/hkxclasses/behavior/hkbbehaviorgraphstringdata.cpp \
    src/hkxclasses/behavior/hkbblendingtransitioneffect.cpp \
    src/hkxclasses/behavior/hkbboneindexarray.cpp \
    src/hkxclasses/behavior/hkbboneweightarray.cpp \
    src/hkxclasses/behavior/hkbcharacterdata.cpp \
    src/hkxclasses/behavior/hkbcharacterstringdata.cpp \
    src/hkxclasses/behavior/hkbcliptriggerarray.cpp \
    src/hkxclasses/behavior/hkbeventrangedataarray.cpp \
    src/hkxclasses/behavior/hkbexpressioncondition.cpp \
    src/hkxclasses/behavior/hkbexpressiondataarray.cpp \
    src/hkxclasses/behavior/hkbfootikdriverinfo.cpp \
    src/hkxclasses/behavior/hkbgeneratortransitioneffect.cpp \
    src/hkxclasses/behavior/hkbhandikdriverinfo.cpp \
    src/hkxclasses/behavior/hkbmirroredskeletoninfo.cpp \
    src/hkxclasses/behavior/hkbprojectdata.cpp \
    src/hkxclasses/behavior/hkbprojectstringdata.cpp \
    src/hkxclasses/behavior/hkbstatemachineeventpropertyarray.cpp \
    src/hkxclasses/behavior/hkbstatemachinetransitioninfoarray.cpp \
    src/hkxclasses/behavior/hkbstringcondition.cpp \
    src/hkxclasses/behavior/hkbstringeventpayload.cpp \
    src/hkxclasses/behavior/hkbvariablebindingset.cpp \
    src/hkxclasses/behavior/hkbvariablevalueset.cpp \
    src/hkxclasses/hkrootlevelcontainer.cpp \
    src/hkxclasses/hksimplelocalframe.cpp \
    src/hkxclasses/hkxobject.cpp \
    src/ui/hkxclassesui/behaviorui/generators/behaviorgraphui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/behaviorreferencegeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/bgsgamebryosequencegeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/blendergeneratorchildui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/blendergeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/bsboneswitchgeneratorbonedataui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/bsboneswitchgeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/bscyclicblendtransitiongeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/bsistatetagginggeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/bsoffsetanimationgeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/bssynchronizedclipgeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/clipgeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/manualselectorgeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/modifiergeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/posematchinggeneratorui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/statemachineui.cpp \
    src/ui/hkxclassesui/behaviorui/generators/stateui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bscomputeaddboneanimmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bsdecomposevectormodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bsdirectatmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bsdisttriggermodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bseventeveryneventsmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bseventondeactivatemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bseventonfalsetotruemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bsgettimestepmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bsinterpvaluemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bsisactivemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bslimbikmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bslookatmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bsmodifyoncemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bspassbytargettriggermodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bsragdollcontactlistenermodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bsspeedsamplermodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bstimermodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/bstweenermodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/combinetransformsmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/computedirectionmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/computerotationfromaxisanglemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/computerotationtotargetmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/dampingmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/delayedmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/detectclosetogroundmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/evaluateexpressionmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/evaluatehandlemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/eventdrivenmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/eventsfromrangemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/extractragdollposemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/footikcontrolsmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/gethandleonbonemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/getupmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/getworldfrommodelmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/handikcontrolsmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/keyframebonesmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/lookatmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/mirrormodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/modifierlistui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/movecharactermodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/poweredragdollcontrolsmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/rigidbodyragdollcontrolsmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/rotatecharactermodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/sensehandlemodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/timermodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/transformvectormodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/modifiers/twistmodifierui.cpp \
    src/ui/hkxclassesui/behaviorui/animationsui.cpp \
    src/ui/hkxclassesui/behaviorui/behaviorgraphicon.cpp \
    src/ui/hkxclassesui/behaviorui/behaviorvariablesui.cpp \
    src/ui/hkxclassesui/behaviorui/blendingtransitioneffectui.cpp \
    src/ui/hkxclassesui/behaviorui/boneindexarrayui.cpp \
    src/ui/hkxclassesui/behaviorui/boneweightarrayui.cpp \
    src/ui/hkxclassesui/behaviorui/bsboneui.cpp \
    src/ui/hkxclassesui/behaviorui/characterpropertiesui.cpp \
    src/ui/hkxclassesui/behaviorui/cliptriggerui.cpp \
    src/ui/hkxclassesui/behaviorui/eventrangedataui.cpp \
    src/ui/hkxclassesui/behaviorui/eventsui.cpp \
    src/ui/hkxclassesui/behaviorui/eventui.cpp \
    src/ui/hkxclassesui/behaviorui/expressiondataarrayui.cpp \
    src/ui/hkxclassesui/behaviorui/footikdriverinfolegui.cpp \
    src/ui/hkxclassesui/behaviorui/footikdriverinfoui.cpp \
    src/ui/hkxclassesui/behaviorui/handikdriverinfohandui.cpp \
    src/ui/hkxclassesui/behaviorui/handikdriverinfoui.cpp \
    src/ui/hkxclassesui/behaviorui/handui.cpp \
    src/ui/hkxclassesui/behaviorui/keyframeinfoui.cpp \
    src/ui/hkxclassesui/behaviorui/legui.cpp \
    src/ui/hkxclassesui/behaviorui/rangesui.cpp \
    src/ui/hkxclassesui/behaviorui/skeletonui.cpp \
    src/ui/hkxclassesui/behaviorui/transitionsui.cpp \
    src/ui/hkxclassesui/hkdataui.cpp \
    src/ui/hkxclassesui/projectui.cpp \
    src/ui/behaviorgraphview.cpp \
    src/ui/dataiconmanager.cpp \
    src/ui/genericdatawidgets.cpp \
    src/ui/mainwindow.cpp \
    src/ui/treegraphicsitem.cpp \
    src/ui/treegraphicsscene.cpp \
    src/ui/treegraphicsview.cpp \
    src/xml/hkxxmlreader.cpp \
    src/xml/hkxxmlwriter.cpp \
    src/main.cpp \
    src/animSetData/skyrimanimsetdata.cpp \
    src/animData/skyrimanimdata.cpp \
    src/animSetData/hkcrc.cpp \
    src/ui/skyrimanimationdataui.cpp \
    src/ui/animationtranslationui.cpp \
    src/ui/animationrotationui.cpp \
    src/animData/projectanimdata.cpp \
    src/animData/skyrimclipgeneratodata.cpp \
    src/animData/skyrimcliptrigger.cpp \
    src/animData/skyrimanimationtranslation.cpp \
    src/animData/skyrimanimationrotation.cpp \
    src/animData/skyrimanimationmotiondata.cpp \
    src/animSetData/animcacheanimationinfo.cpp \
    src/animSetData/animcacheclipinfo.cpp \
    src/animSetData/animcachevariable.cpp \
    src/animSetData/animcacheanimsetdata.cpp \
    src/animSetData/animcacheprojectdata.cpp \
    src/filetypes/animationfile.cpp \
    src/ui/hkxclassesui/animationcacheui.cpp

HEADERS  += \
    src/filetypes/hkxfile.h \
    src/ui/mainwindow.h \
    src/xml/hkxxmlreader.h \
    src/hkxclasses/behavior/hkbbehaviorgraphstringdata.h \
    src/hkxclasses/hkxobject.h \
    src/hkxclasses/behavior/hkbvariablevalueset.h \
    src/hkxclasses/behavior/hkbbehaviorgraphdata.h \
    src/hkxclasses/behavior/generators/hkbbehaviorgraph.h \
    src/hkxclasses/behavior/generators/hkbgenerator.h \
    src/hkxclasses/hkrootlevelcontainer.h \
    src/hkxclasses/behavior/generators/hkbbehaviorreferencegenerator.h \
    src/hkxclasses/behavior/generators/hkbstatemachine.h \
    src/hkxclasses/behavior/generators/hkbstatemachinestateinfo.h \
    src/hkxclasses/behavior/generators/hkbclipgenerator.h \
    src/hkxclasses/behavior/generators/bscyclicblendtransitiongenerator.h \
    src/hkxclasses/behavior/generators/hkbblendergenerator.h \
    src/hkxclasses/behavior/generators/hkbblendergeneratorchild.h \
    src/hkxclasses/behavior/generators/hkbmanualselectorgenerator.h \
    src/hkxclasses/behavior/generators/hkbmodifiergenerator.h \
    src/hkxclasses/behavior/generators/bsboneswitchgenerator.h \
    src/hkxclasses/behavior/generators/bsboneswitchgeneratorbonedata.h \
    src/hkxclasses/behavior/generators/bsistatetagginggenerator.h \
    src/hkxclasses/behavior/generators/bssynchronizedclipgenerator.h \
    src/hkxclasses/behavior/generators/hkbposematchinggenerator.h \
    src/hkxclasses/behavior/generators/bsoffsetanimationgenerator.h \
    src/hkxclasses/behavior/hkbstringeventpayload.h \
    src/hkxclasses/behavior/hkbboneweightarray.h \
    src/hkxclasses/behavior/hkbstatemachineeventpropertyarray.h \
    src/hkxclasses/behavior/hkbstatemachinetransitioninfoarray.h \
    src/ui/genericdatawidgets.h \
    src/hkxclasses/behavior/modifiers/hkbmodifier.h \
    src/ui/hkxclassesui/hkdataui.h \
    src/ui/hkxclassesui/behaviorui/generators/bsistatetagginggeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/modifiergeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/manualselectorgeneratorui.h \
    src/ui/hkxclassesui/behaviorui/behaviorvariablesui.h \
    src/utility.h \
    src/ui/hkxclassesui/behaviorui/eventsui.h \
    src/ui/hkxclassesui/behaviorui/generators/statemachineui.h \
    src/ui/hkxclassesui/behaviorui/generators/stateui.h \
    src/hkxclasses/behavior/hkbvariablebindingset.h \
    src/ui/hkxclassesui/behaviorui/transitionsui.h \
    src/ui/hkxclassesui/behaviorui/blendingtransitioneffectui.h \
    src/hkxclasses/behavior/hkbexpressioncondition.h \
    src/xml/hkxxmlwriter.h \
    src/hkxclasses/behavior/hkbcliptriggerarray.h \
    src/hkxclasses/behavior/hkbblendingtransitioneffect.h \
    src/hkxclasses/behavior/modifiers/hkbmodifierlist.h \
    src/hkxclasses/behavior/modifiers/hkbtwistmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbeventdrivenmodifier.h \
    src/hkxclasses/behavior/modifiers/bsisactivemodifier.h \
    src/hkxclasses/behavior/modifiers/bslimbikmodifier.h \
    src/hkxclasses/behavior/modifiers/bsspeedsamplermodifier.h \
    src/hkxclasses/behavior/modifiers/bslookatmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbfootikcontrolsmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbevaluateexpressionmodifier.h \
    src/hkxclasses/behavior/hkbexpressiondataarray.h \
    src/hkxclasses/behavior/modifiers/bsmodifyoncemodifier.h \
    src/hkxclasses/behavior/modifiers/hkbrotatecharactermodifier.h \
    src/hkxclasses/behavior/modifiers/bseventondeactivatemodifier.h \
    src/hkxclasses/behavior/modifiers/hkbdampingmodifier.h \
    src/hkxclasses/behavior/modifiers/bseventonfalsetotruemodifier.h \
    src/hkxclasses/behavior/modifiers/hkbkeyframebonesmodifier.h \
    src/hkxclasses/behavior/hkbboneindexarray.h \
    src/hkxclasses/behavior/modifiers/bsragdollcontactlistenermodifier.h \
    src/hkxclasses/behavior/modifiers/hkbpoweredragdollcontrolsmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbtimermodifier.h \
    src/hkxclasses/behavior/modifiers/hkbrigidbodyragdollcontrolsmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbgetupmodifier.h \
    src/hkxclasses/behavior/modifiers/bsdirectatmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbcomputedirectionmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbevaluatehandlemodifier.h \
    src/hkxclasses/behavior/modifiers/hkbgethandleonbonemodifier.h \
    src/hkxclasses/behavior/modifiers/hkbsensehandlemodifier.h \
    src/hkxclasses/behavior/modifiers/hkbdelayedmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbdetectclosetogroundmodifier.h \
    src/hkxclasses/behavior/modifiers/bsdecomposevectormodifier.h \
    src/hkxclasses/behavior/generators/bgsgamebryosequencegenerator.h \
    src/hkxclasses/behavior/modifiers/bscomputeaddboneanimmodifier.h \
    src/hkxclasses/behavior/modifiers/bsdisttriggermodifier.h \
    src/hkxclasses/behavior/modifiers/bseventeveryneventsmodifier.h \
    src/hkxclasses/behavior/modifiers/bsgettimestepmodifier.h \
    src/hkxclasses/behavior/modifiers/bsinterpvaluemodifier.h \
    src/hkxclasses/behavior/modifiers/bspassbytargettriggermodifier.h \
    src/hkxclasses/behavior/modifiers/bstimermodifier.h \
    src/hkxclasses/behavior/modifiers/bstweenermodifier.h \
    src/hkxclasses/behavior/modifiers/hkbattachmentmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbattributemodifier.h \
    src/hkxclasses/behavior/modifiers/hkbcombinetransformsmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbcomputerotationfromaxisanglemodifier.h \
    src/hkxclasses/behavior/modifiers/hkbcomputerotationtotargetmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbeventsfromrangemodifier.h \
    src/hkxclasses/behavior/hkbeventrangedataarray.h \
    src/hkxclasses/behavior/modifiers/hkbextractragdollposemodifier.h \
    src/hkxclasses/behavior/hkbgeneratortransitioneffect.h \
    src/hkxclasses/behavior/modifiers/hkbgetworldfrommodelmodifier.h \
    src/hkxclasses/behavior/modifiers/hkblookatmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbmirrormodifier.h \
    src/hkxclasses/behavior/modifiers/hkbmovecharactermodifier.h \
    src/hkxclasses/behavior/modifiers/hkbtransformvectormodifier.h \
    src/hkxclasses/behavior/modifiers/hkbproxymodifier.h \
    src/hkxclasses/behavior/modifiers/bsistatemanagermodifier.h \
    src/filetypes/behaviorfile.h \
    src/filetypes/projectfile.h \
    src/filetypes/characterfile.h \
    src/filetypes/skeletonfile.h \
    src/hkxclasses/behavior/hkbprojectdata.h \
    src/hkxclasses/behavior/hkbprojectstringdata.h \
    src/hkxclasses/behavior/hkbmirroredskeletoninfo.h \
    src/hkxclasses/behavior/hkbcharacterstringdata.h \
    src/hkxclasses/behavior/hkbcharacterdata.h \
    src/hkxclasses/behavior/hkbfootikdriverinfo.h \
    src/hkxclasses/behavior/hkbhandikdriverinfo.h \
    src/hkxclasses/behavior/hkbstringcondition.h \
    src/ui/hkxclassesui/projectui.h \
    src/hkxclasses/animation/hkaanimationcontainer.h \
    src/hkxclasses/hksimplelocalframe.h \
    src/hkxclasses/animation/hkaskeleton.h \
    src/ui/hkxclassesui/behaviorui/boneweightarrayui.h \
    src/ui/hkxclassesui/behaviorui/characterpropertiesui.h \
    src/ui/hkxclassesui/behaviorui/skeletonui.h \
    src/ui/hkxclassesui/behaviorui/footikdriverinfoui.h \
    src/ui/hkxclassesui/behaviorui/footikdriverinfolegui.h \
    src/ui/hkxclassesui/behaviorui/handikdriverinfoui.h \
    src/ui/hkxclassesui/behaviorui/handikdriverinfohandui.h \
    src/ui/hkxclassesui/behaviorui/generators/blendergeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/blendergeneratorchildui.h \
    src/ui/dataiconmanager.h \
    src/ui/treegraphicsscene.h \
    src/ui/treegraphicsview.h \
    src/ui/treegraphicsitem.h \
    src/ui/behaviorgraphview.h \
    src/ui/hkxclassesui/behaviorui/eventui.h \
    src/ui/hkxclassesui/behaviorui/behaviorgraphicon.h \
    src/ui/hkxclassesui/behaviorui/generators/behaviorgraphui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bslimbikmodifierui.h \
    src/ui/hkxclassesui/behaviorui/generators/bsboneswitchgeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/bsboneswitchgeneratorbonedataui.h \
    src/ui/hkxclassesui/behaviorui/generators/bsoffsetanimationgeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/bscyclicblendtransitiongeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/posematchinggeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/clipgeneratorui.h \
    src/ui/hkxclassesui/behaviorui/cliptriggerui.h \
    src/ui/hkxclassesui/behaviorui/animationsui.h \
    src/ui/hkxclassesui/behaviorui/generators/bssynchronizedclipgeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/behaviorreferencegeneratorui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bsdirectatmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/movecharactermodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/rotatecharactermodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/evaluateexpressionmodifierui.h \
    src/ui/hkxclassesui/behaviorui/expressiondataarrayui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/modifierlistui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/eventdrivenmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/gethandleonbonemodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/evaluatehandlemodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/sensehandlemodifierui.h \
    src/ui/hkxclassesui/behaviorui/rangesui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bsdecomposevectormodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bsisactivemodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/computedirectionmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bscomputeaddboneanimmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bsdisttriggermodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bsinterpvaluemodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/computerotationtotargetmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/getupmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/getworldfrommodelmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/twistmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/timermodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/dampingmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/rigidbodyragdollcontrolsmodifierui.h \
    src/ui/hkxclassesui/behaviorui/boneindexarrayui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/poweredragdollcontrolsmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/combinetransformsmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/computerotationfromaxisanglemodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/transformvectormodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/lookatmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/keyframebonesmodifierui.h \
    src/ui/hkxclassesui/behaviorui/keyframeinfoui.h \
    src/ui/hkxclassesui/behaviorui/legui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/footikcontrolsmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/mirrormodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/extractragdollposemodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bstimermodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bsgettimestepmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/delayedmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bsragdollcontactlistenermodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bseventondeactivatemodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bsspeedsamplermodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bspassbytargettriggermodifierui.h \
    src/ui/hkxclassesui/behaviorui/bsboneui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bslookatmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/detectclosetogroundmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bseventeveryneventsmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bseventonfalsetotruemodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bsmodifyoncemodifierui.h \
    src/hkxclasses/behavior/modifiers/hkbhandikcontrolsmodifier.h \
    src/ui/hkxclassesui/behaviorui/handui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/handikcontrolsmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bstweenermodifierui.h \
    src/ui/hkxclassesui/behaviorui/generators/bgsgamebryosequencegeneratorui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/eventsfromrangemodifierui.h \
    src/ui/hkxclassesui/behaviorui/eventrangedataui.h \
    src/filetypes/behaviorfile.h \
    src/filetypes/characterfile.h \
    src/filetypes/hkxfile.h \
    src/filetypes/projectfile.h \
    src/filetypes/skeletonfile.h \
    src/hkxclasses/animation/hkaanimationcontainer.h \
    src/hkxclasses/animation/hkaskeleton.h \
    src/hkxclasses/behavior/generators/bgsgamebryosequencegenerator.h \
    src/hkxclasses/behavior/generators/bsboneswitchgenerator.h \
    src/hkxclasses/behavior/generators/bsboneswitchgeneratorbonedata.h \
    src/hkxclasses/behavior/generators/bscyclicblendtransitiongenerator.h \
    src/hkxclasses/behavior/generators/bsistatetagginggenerator.h \
    src/hkxclasses/behavior/generators/bsoffsetanimationgenerator.h \
    src/hkxclasses/behavior/generators/bssynchronizedclipgenerator.h \
    src/hkxclasses/behavior/generators/hkbbehaviorgraph.h \
    src/hkxclasses/behavior/generators/hkbbehaviorreferencegenerator.h \
    src/hkxclasses/behavior/generators/hkbblendergenerator.h \
    src/hkxclasses/behavior/generators/hkbblendergeneratorchild.h \
    src/hkxclasses/behavior/generators/hkbclipgenerator.h \
    src/hkxclasses/behavior/generators/hkbgenerator.h \
    src/hkxclasses/behavior/generators/hkbmanualselectorgenerator.h \
    src/hkxclasses/behavior/generators/hkbmodifiergenerator.h \
    src/hkxclasses/behavior/generators/hkbposematchinggenerator.h \
    src/hkxclasses/behavior/generators/hkbstatemachine.h \
    src/hkxclasses/behavior/generators/hkbstatemachinestateinfo.h \
    src/hkxclasses/behavior/modifiers/bscomputeaddboneanimmodifier.h \
    src/hkxclasses/behavior/modifiers/bsdecomposevectormodifier.h \
    src/hkxclasses/behavior/modifiers/bsdirectatmodifier.h \
    src/hkxclasses/behavior/modifiers/bsdisttriggermodifier.h \
    src/hkxclasses/behavior/modifiers/bseventeveryneventsmodifier.h \
    src/hkxclasses/behavior/modifiers/bseventondeactivatemodifier.h \
    src/hkxclasses/behavior/modifiers/bseventonfalsetotruemodifier.h \
    src/hkxclasses/behavior/modifiers/bsgettimestepmodifier.h \
    src/hkxclasses/behavior/modifiers/bsinterpvaluemodifier.h \
    src/hkxclasses/behavior/modifiers/bsisactivemodifier.h \
    src/hkxclasses/behavior/modifiers/bsistatemanagermodifier.h \
    src/hkxclasses/behavior/modifiers/bslimbikmodifier.h \
    src/hkxclasses/behavior/modifiers/bslookatmodifier.h \
    src/hkxclasses/behavior/modifiers/bsmodifyoncemodifier.h \
    src/hkxclasses/behavior/modifiers/bspassbytargettriggermodifier.h \
    src/hkxclasses/behavior/modifiers/bsragdollcontactlistenermodifier.h \
    src/hkxclasses/behavior/modifiers/bsspeedsamplermodifier.h \
    src/hkxclasses/behavior/modifiers/bstimermodifier.h \
    src/hkxclasses/behavior/modifiers/bstweenermodifier.h \
    src/hkxclasses/behavior/modifiers/hkbattachmentmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbattributemodifier.h \
    src/hkxclasses/behavior/modifiers/hkbcombinetransformsmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbcomputedirectionmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbcomputerotationfromaxisanglemodifier.h \
    src/hkxclasses/behavior/modifiers/hkbcomputerotationtotargetmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbdampingmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbdelayedmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbdetectclosetogroundmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbevaluateexpressionmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbevaluatehandlemodifier.h \
    src/hkxclasses/behavior/modifiers/hkbeventdrivenmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbeventsfromrangemodifier.h \
    src/hkxclasses/behavior/modifiers/hkbextractragdollposemodifier.h \
    src/hkxclasses/behavior/modifiers/hkbfootikcontrolsmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbgethandleonbonemodifier.h \
    src/hkxclasses/behavior/modifiers/hkbgetupmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbgetworldfrommodelmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbhandikcontrolsmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbkeyframebonesmodifier.h \
    src/hkxclasses/behavior/modifiers/hkblookatmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbmirrormodifier.h \
    src/hkxclasses/behavior/modifiers/hkbmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbmodifierlist.h \
    src/hkxclasses/behavior/modifiers/hkbmovecharactermodifier.h \
    src/hkxclasses/behavior/modifiers/hkbpoweredragdollcontrolsmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbproxymodifier.h \
    src/hkxclasses/behavior/modifiers/hkbrigidbodyragdollcontrolsmodifier.h \
    src/hkxclasses/behavior/modifiers/hkbrotatecharactermodifier.h \
    src/hkxclasses/behavior/modifiers/hkbsensehandlemodifier.h \
    src/hkxclasses/behavior/modifiers/hkbtimermodifier.h \
    src/hkxclasses/behavior/modifiers/hkbtransformvectormodifier.h \
    src/hkxclasses/behavior/modifiers/hkbtwistmodifier.h \
    src/hkxclasses/behavior/hkbbehaviorgraphdata.h \
    src/hkxclasses/behavior/hkbbehaviorgraphstringdata.h \
    src/hkxclasses/behavior/hkbblendingtransitioneffect.h \
    src/hkxclasses/behavior/hkbboneindexarray.h \
    src/hkxclasses/behavior/hkbboneweightarray.h \
    src/hkxclasses/behavior/hkbcharacterdata.h \
    src/hkxclasses/behavior/hkbcharacterstringdata.h \
    src/hkxclasses/behavior/hkbcliptriggerarray.h \
    src/hkxclasses/behavior/hkbeventrangedataarray.h \
    src/hkxclasses/behavior/hkbexpressioncondition.h \
    src/hkxclasses/behavior/hkbexpressiondataarray.h \
    src/hkxclasses/behavior/hkbfootikdriverinfo.h \
    src/hkxclasses/behavior/hkbgeneratortransitioneffect.h \
    src/hkxclasses/behavior/hkbhandikdriverinfo.h \
    src/hkxclasses/behavior/hkbmirroredskeletoninfo.h \
    src/hkxclasses/behavior/hkbprojectdata.h \
    src/hkxclasses/behavior/hkbprojectstringdata.h \
    src/hkxclasses/behavior/hkbstatemachineeventpropertyarray.h \
    src/hkxclasses/behavior/hkbstatemachinetransitioninfoarray.h \
    src/hkxclasses/behavior/hkbstringcondition.h \
    src/hkxclasses/behavior/hkbstringeventpayload.h \
    src/hkxclasses/behavior/hkbvariablebindingset.h \
    src/hkxclasses/behavior/hkbvariablevalueset.h \
    src/hkxclasses/hkrootlevelcontainer.h \
    src/hkxclasses/hksimplelocalframe.h \
    src/hkxclasses/hkxobject.h \
    src/ui/hkxclassesui/behaviorui/generators/behaviorgraphui.h \
    src/ui/hkxclassesui/behaviorui/generators/behaviorreferencegeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/bgsgamebryosequencegeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/blendergeneratorchildui.h \
    src/ui/hkxclassesui/behaviorui/generators/blendergeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/bsboneswitchgeneratorbonedataui.h \
    src/ui/hkxclassesui/behaviorui/generators/bsboneswitchgeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/bscyclicblendtransitiongeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/bsistatetagginggeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/bsoffsetanimationgeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/bssynchronizedclipgeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/clipgeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/manualselectorgeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/modifiergeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/posematchinggeneratorui.h \
    src/ui/hkxclassesui/behaviorui/generators/statemachineui.h \
    src/ui/hkxclassesui/behaviorui/generators/stateui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bscomputeaddboneanimmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bsdecomposevectormodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bsdirectatmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bsdisttriggermodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bseventeveryneventsmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bseventondeactivatemodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bseventonfalsetotruemodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bsgettimestepmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bsinterpvaluemodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bsisactivemodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bslimbikmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bslookatmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bsmodifyoncemodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bspassbytargettriggermodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bsragdollcontactlistenermodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bsspeedsamplermodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bstimermodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/bstweenermodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/combinetransformsmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/computedirectionmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/computerotationfromaxisanglemodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/computerotationtotargetmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/dampingmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/delayedmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/detectclosetogroundmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/evaluateexpressionmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/evaluatehandlemodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/eventdrivenmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/eventsfromrangemodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/extractragdollposemodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/footikcontrolsmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/gethandleonbonemodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/getupmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/getworldfrommodelmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/handikcontrolsmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/keyframebonesmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/lookatmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/mirrormodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/modifierlistui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/movecharactermodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/poweredragdollcontrolsmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/rigidbodyragdollcontrolsmodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/rotatecharactermodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/sensehandlemodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/timermodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/transformvectormodifierui.h \
    src/ui/hkxclassesui/behaviorui/modifiers/twistmodifierui.h \
    src/ui/hkxclassesui/behaviorui/animationsui.h \
    src/ui/hkxclassesui/behaviorui/behaviorgraphicon.h \
    src/ui/hkxclassesui/behaviorui/behaviorvariablesui.h \
    src/ui/hkxclassesui/behaviorui/blendingtransitioneffectui.h \
    src/ui/hkxclassesui/behaviorui/boneindexarrayui.h \
    src/ui/hkxclassesui/behaviorui/boneweightarrayui.h \
    src/ui/hkxclassesui/behaviorui/bsboneui.h \
    src/ui/hkxclassesui/behaviorui/characterpropertiesui.h \
    src/ui/hkxclassesui/behaviorui/cliptriggerui.h \
    src/ui/hkxclassesui/behaviorui/eventrangedataui.h \
    src/ui/hkxclassesui/behaviorui/eventsui.h \
    src/ui/hkxclassesui/behaviorui/eventui.h \
    src/ui/hkxclassesui/behaviorui/expressiondataarrayui.h \
    src/ui/hkxclassesui/behaviorui/footikdriverinfolegui.h \
    src/ui/hkxclassesui/behaviorui/footikdriverinfoui.h \
    src/ui/hkxclassesui/behaviorui/handikdriverinfohandui.h \
    src/ui/hkxclassesui/behaviorui/handikdriverinfoui.h \
    src/ui/hkxclassesui/behaviorui/handui.h \
    src/ui/hkxclassesui/behaviorui/keyframeinfoui.h \
    src/ui/hkxclassesui/behaviorui/legui.h \
    src/ui/hkxclassesui/behaviorui/rangesui.h \
    src/ui/hkxclassesui/behaviorui/skeletonui.h \
    src/ui/hkxclassesui/behaviorui/transitionsui.h \
    src/ui/hkxclassesui/hkdataui.h \
    src/ui/hkxclassesui/projectui.h \
    src/ui/behaviorgraphview.h \
    src/ui/dataiconmanager.h \
    src/ui/genericdatawidgets.h \
    src/ui/mainwindow.h \
    src/ui/treegraphicsitem.h \
    src/ui/treegraphicsscene.h \
    src/ui/treegraphicsView.h \
    src/xml/hkxxmlreader.h \
    src/xml/hkxxmlwriter.h \
    src/utility.h \
    src/animSetData/skyrimanimsetdata.h \
    src/animData/skyrimanimdata.h \
    src/animSetData/hkcrc.h \
    src/ui/skyrimanimationdataui.h \
    src/ui/animationtranslationui.h \
    src/ui/animationrotationui.h \
    src/animData/projectanimdata.h \
    src/animData/skyrimclipgeneratodata.h \
    src/animData/skyrimcliptrigger.h \
    src/animData/skyrimanimationtranslation.h \
    src/animData/skyrimanimationrotation.h \
    src/animData/skyrimanimationmotiondata.h \
    src/animSetData/animcacheanimationinfo.h \
    src/animSetData/animcacheclipinfo.h \
    src/animSetData/animcachevariable.h \
    src/animSetData/animcacheanimsetdata.h \
    src/animSetData/animcacheprojectdata.h \
    src/filetypes/animationfile.h \
    src/ui/hkxclassesui/animationcacheui.h
