#ifndef COMPUTEROTATIONTOTARGETMODIFIERUI_H
#define COMPUTEROTATIONTOTARGETMODIFIERUI_H


class ComputeRotationToTargetModifierUI
{
public:
    ComputeRotationToTargetModifierUI();
};

#endif // COMPUTEROTATIONTOTARGETMODIFIERUI_H